services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 3000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 6
    depends_on:
      - zookeeper

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

  spring-app-1:
    image: splguyjr/momentum-be:latest
    container_name: momentum-be
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_NOTIFICATION_TOPIC: ${KAFKA_NOTIFICATION_TOPIC}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION}
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      CLOUDFRONT_PRIVATE_KEY_PATH: /app/cert/cloudfront_private_key.pem
      NAVER_URL: ${NAVER_URL}
      NAVER_SECRET_KEY: ${NAVER_SECRET_KEY}
      BATCH_SERVER_URL: ${BATCH_SERVER_URL}
    volumes:
      - ./cert/cloudfront_private_key.pem:/app/cert/cloudfront_private_key.pem:ro
    depends_on:
      - kafka
      - redis

  spring-app-2:
    image: splguyjr/momentum-notification:latest
    container_name: momentum-notification
    ports:
      - "8081:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_CONSUMER_GROUP_ID: ${KAFKA_CONSUMER_GROUP_ID}
      KAFKA_NOTIFICATION_TOPIC: ${KAFKA_NOTIFICATION_TOPIC}
      KAFKA_EVALUATION_NOTIFICATION_TOPIC: ${KAFKA_EVALUATION_NOTIFICATION_TOPIC}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION}
    depends_on:
      - kafka
      - redis

  spring-batch:
    image: splguyjr/momentum-batch:latest
    container_name: momentum-batch
    ports:
      - "8082:8080"
    restart: on-failure
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_EVALUATION_NOTIFICATION_TOPIC: ${KAFKA_EVALUATION_NOTIFICATION_TOPIC}
      EVALUATION_SERVICE_URL: http://spring-app-1:8080
      BATCH_JWT_TOKEN: ${BATCH_JWT_TOKEN}
    depends_on:
      - kafka
      - redis
      - spring-app-1

networks:
  default:
    name: spring-kafka-net